name: develop-release

on:
  push:
    branches:
      - develop

jobs:
  docker-release:
    uses: smeup/devops/.github/workflows/docker-release.yaml@main
    with:
      docker-tag: latest
      docker-repository-name: kokos-node-workshop
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}